steps:
  # Install dependencies
  - name: node
    entrypoint: npm
    args: ['install']
  # Run tests
  - name: node
    entrypoint: npm
    args: ['test']
    env:
      - 'CI=true'
  # Run custom commands
  - name: node
    entrypoint: npm
    args: ['run', 'build']
  # Deploy
  - name: gcr.io/cloud-builders/gsutil
    args: ['-m', 'rsync', '-r', '-c' , '-d', './build', 'gs://gcp.weirdwares.com']
